apiVersion: apps/v1
kind: Deployment
metadata:
  name: thymeleafpoc-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thymeleafpoc
  template:
    metadata:
      labels:
        app: thymeleafpoc
    spec:
      containers:
        - name: thymeleafpoc-container
          image: rsiv5588/thymeleafpoc:latest
          ports:
            - containerPort: 8084

