apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: thymeleafpoc
build:
  artifacts:
    - image: rsiv5588/thymeleafpoc
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - deployment.yaml
    - service.yaml
